exclude_paths:
  - "**/*.md"
  - "*.md"

engines:
  duplication:
    enabled: true
    exclude_paths:
      - '**/*Response.kt'
      - '**/*Adapter.kt'
      - '**/build.gradle.kts'      
      - '**/I*Repository.kt'