name: Android Instrumentation Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  android_test:
    name: Running Android Tests
    runs-on: macos-13
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          target: default
          arch: x86_64
          profile: Nexus 4
          emulator-options: -no-window -no-boot-anim -no-audio -no-snapshot-load
          script: |
            adb wait-for-device
            adb shell input keyevent 82
            ./gradlew :app:connectedAndroidTest --info --continue

      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-report
          path: '**/build/reports/androidTests/connected/'