name: testing
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**.md'

jobs:
  detekt_checks:
    name: Detekt Checks
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Get local.properties from secrets
        run: echo "${{secrets.LOCAL_PROPERTIES }}" > $GITHUB_WORKSPACE/local.properties

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Google Service
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          cat /home/runner/work/BAZZ-Movies/BAZZ-Movies/app/google-services.json | base64
          echo $DATA > /home/runner/work/BAZZ-Movies/BAZZ-Movies/app/google-services.json

      - name: Run Detekt
        run: ./gradlew detekt

  unit_test:
    name: Unit Tests
    needs: detekt_checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: true
    permissions:
      contents: read
      actions: write # Needed for cache and artifact upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Get local.properties from secrets
        run: echo "${{secrets.LOCAL_PROPERTIES }}" > $GITHUB_WORKSPACE/local.properties

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Google Service
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          cat /home/runner/work/BAZZ-Movies/BAZZ-Movies/app/google-services.json | base64
          echo $DATA > /home/runner/work/BAZZ-Movies/BAZZ-Movies/app/google-services.json

      - name: Run debug unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      # Cache unit test results for the coverage job
      - name: Cache unit test results
        uses: actions/cache/save@v4
        if: always() # Save cache even if tests fail
        with:
          path: |
            ${{ github.workspace }}/**/build/outputs/unit_test_code_coverage/
            ${{ github.workspace }}/**/build/reports/tests/testDebugUnitTest/
            ${{ github.workspace }}/**/build/test-results/testDebugUnitTest/
            ${{ github.workspace }}/**/build/tmp/kotlin-classes/
          key: unit-test-results-${{ github.run_id }}

      - name: Upload Unit Test Reports (if needed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: '**/build/reports/tests/testDebugUnitTest/'

  instrumentation_test:
    name: Instrumentation Tests
    needs: detekt_checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: true
    permissions:
      contents: read
      actions: write # Needed for cache and artifact upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Get local.properties from secrets
        run: echo "${{secrets.LOCAL_PROPERTIES }}" > $GITHUB_WORKSPACE/local.properties

      - name: Google Service
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          cat /home/runner/work/BAZZ-Movies/BAZZ-Movies/app/google-services.json | base64
          echo $DATA > /home/runner/work/BAZZ-Movies/BAZZ-Movies/app/google-services.json

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      # https://github.com/ReactiveCircus/android-emulator-runner/commit/1dcd0090116d15e7c562f8db72807de5e036a4ed
      # v2.34.0
      - name: Run instrumentation test
        uses: reactivecircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed
        with:
          api-level: 29
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: |
            adb wait-for-device
            ./gradlew :feature:login:connectedDebugAndroidTest --stacktrace
            adb devices | grep emulator | cut -f1 | while read line; do adb -s $line emu kill; done
            pkill -f emulator || true
            pkill -f qemu || true

      # Cache instrumentation test results for the coverage job
      - name: Cache instrumentation test results
        uses: actions/cache/save@v4
        if: always() # Save cache even if tests fail
        with:
          path: |
            ${{ github.workspace }}/**/build/outputs/androidTest-results/
            ${{ github.workspace }}/**/build/outputs/code_coverage/
            ${{ github.workspace }}/**/build/reports/androidTests/
            ${{ github.workspace }}/**/build/test-results/connectedDebugAndroidTest/
            ${{ github.workspace }}/**/build/tmp/kotlin-classes/debug/
            ${{ github.workspace }}/**/build/tmp/kotlin-classes/debugAndroidTest/
          key: instrumentation-test-results-${{ github.run_id }}

      - name: Upload Instrumentation Test Reports (if needed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: instrumentation-test-report
          path: '**/build/reports/androidTests/connected/'

  test_coverage:
    name: Test Coverage Report
    needs: [unit_test, instrumentation_test]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: true
    permissions:
      contents: read
      actions: write # Needed for cache and artifact upload
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Get local.properties from secrets
        run: echo "${{secrets.LOCAL_PROPERTIES }}" > $GITHUB_WORKSPACE/local.properties

      - name: Google Service
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          cat /home/runner/work/BAZZ-Movies/BAZZ-Movies/app/google-services.json | base64
          echo $DATA > /home/runner/work/BAZZ-Movies/BAZZ-Movies/app/google-services.json

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # Restore cached unit test results
      - name: Restore unit test results
        id: cache_restore_unit
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/**/build/outputs/unit_test_code_coverage/
            ${{ github.workspace }}/**/build/reports/tests/testDebugUnitTest/
            ${{ github.workspace }}/**/build/test-results/testDebugUnitTest/
            ${{ github.workspace }}/**/build/tmp/kotlin-classes/
          key: unit-test-results-${{ github.run_id }}

      # Restore cached instrumentation test results
      - name: Restore instrumentation test results
        id: cache_restore_instrumentation
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ github.workspace }}/**/build/outputs/androidTest-results/
            ${{ github.workspace }}/**/build/outputs/code_coverage/
            ${{ github.workspace }}/**/build/reports/androidTests/
            ${{ github.workspace }}/**/build/test-results/connectedDebugAndroidTest/
            ${{ github.workspace }}/**/build/tmp/kotlin-classes/debug/
            ${{ github.workspace }}/**/build/tmp/kotlin-classes/debugAndroidTest/
          key: instrumentation-test-results-${{ github.run_id }}

      # Fallback: run unit tests if cache missed
      - name: Run debug unit tests (fallback)
        if: steps.cache_restore_unit.outputs.cache-hit != 'true'
        run: ./gradlew testDebugUnitTest --stacktrace

      # Fallback: run instrumentation tests if cache missed
      - name: Enable KVM (fallback)
        if: steps.cache_restore_instrumentation.outputs.cache-hit != 'true'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run debug instrumentation test (fallback)
        if: steps.cache_restore_instrumentation.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed
        with:
          api-level: 29
          arch: x86
          disable-animations: true
          script: |
            adb wait-for-device
            ./gradlew :feature:login:connectedDebugAndroidTest --stacktrace

      - name: Check cached test results
        run: |
          echo "=== Checking Unit Test Results ==="
          find . -name "testDebugUnitTest.exec" -type f || echo "No unit test .exec files found"
          find . -path "*/build/test-results/testDebugUnitTest" -type d || echo "No unit test results found"
          
          echo "=== Checking Instrumentation Test Results ==="
          find . -name "connectedDebugAndroidTest.exec" -type f || echo "No instrumentation test .exec files found"
          find . -path "*/build/test-results/connectedDebugAndroidTest" -type d || echo "No instrumentation test results found"

      - name: Generate JaCoCo Combined Coverage Report
        run: |
          echo "Generating combined coverage report..."
          ./gradlew createDebugCombinedCoverageReport --stacktrace
          
          echo "=== Checking Generated Reports ==="
          find . -name "createDebugCombinedCoverageReport.xml" -type f || echo "No combined coverage report found"
          find . -path "*/build/reports/jacoco" -type d || echo "No jacoco reports directory found"

      # Check if coverage report exists before uploading
      - name: Check coverage report exists
        id: check_coverage
        run: |
          if find . -name "createDebugCombinedCoverageReport.xml" -type f | grep -q .; then
            echo "coverage_exists=true" >> $GITHUB_OUTPUT
            echo "✅ Coverage report found"
            find . -name "createDebugCombinedCoverageReport.xml" -type f
          else
            echo "coverage_exists=false" >> $GITHUB_OUTPUT
            echo "❌ Coverage report not found"
          fi

      # https://github.com/codecov/codecov-action/commit/0565863a31f2c772f9f0395002a31e3f06189574
      # v5.4.0
      - name: Upload coverage reports to Codecov
        if: steps.check_coverage.outputs.coverage_exists == 'true'
        uses: codecov/codecov-action@78f372e97e6e2f82dc51b004c5fb646501ee30ae
        with:
          files: ${{ github.workspace }}/**/build/reports/jacoco/createDebugCombinedCoverageReport/createDebugCombinedCoverageReport.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      # https://github.com/codacy/codacy-coverage-reporter-action/commit/55c3b57cb3bb6833c8c1a6614fee4cebb140de2d
      # v1.3.0
      - name: Upload coverage reports to Codacy
        if: steps.check_coverage.outputs.coverage_exists == 'true'
        uses: codacy/codacy-coverage-reporter-action@a38818475bb21847788496e9f0fddaa4e84955ba
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ${{ github.workspace }}/**/build/reports/jacoco/createDebugCombinedCoverageReport/createDebugCombinedCoverageReport.xml

      # https://github.com/codecov/test-results-action/commit/f2dba722c67b86c6caa034178c6e4d35335f6706
      # v1.1.0
      - name: Upload Unit Test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Test Reports (if needed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: combined-test-reports
          path: |
            **/build/reports/tests/testDebugUnitTest/
            **/build/reports/androidTests/connected/
